import {
    AboutSlint,
    VerticalBox,
    Button,
    HorizontalBox,
    StandardButton,
    Button,
    Palette,
    ScrollView,
    Switch,
    RadioGroup,
} from "std-widgets.slint";
import { AlertDialog, InfoCard } from "widgets.slint";



export component MainWindow inherits Window {
    callback button_clicked();
    preferred-height: 768px;
    preferred-width: 1024px;
    max-width: 100000px;
    max-height: 100000px;
    background: #E2E2E9;

    in-out property <bool> onlineStatus;
    in-out property <bool> nvidiaStatus;
    in-out property <bool> nvidiaStatusAfterReboot;
    in-out property <int> perfMode:-1;
    in-out property <bool> modeRadioGroupEnabled:false;
    in-out property <float> cpuFanRatio:-1;
    in-out property <float> gpuFanRatio:-1;
    in-out property <int> cpuFan:-1;
    in-out property <int> gpuFan:-1;

    in-out property <bool> show_reboot_alert;
    // 应用完成初始化
    in-out property <bool> initialized: false;

    callback onlineStatusToggled(bool);
    callback gpuToggled(bool);
    callback perfModeChange(int);
    callback reboot();

    ScrollView {
        HorizontalLayout {
            // 左栏
            VerticalBox {
                alignment: start;
                Text {
                    text: "Control Panel";
                    font-size: 36px;
                }

                Rectangle {
                    height: self.preferred-height;
                    background: #FFFFFF;
                    border-radius: 8px;
                    HorizontalBox {
                        Text {
                            text: "控制台在线状态";
                            font-size: 16px;
                        }

                        Switch {
                            checked <=> onlineStatus;
                            toggled => { onlineStatusToggled(onlineStatus) }
                        }
                    }
                }

                Rectangle {
                    height: self.preferred-height;
                    background: #FFFFFF;
                    border-radius: 8px;
                    HorizontalBox {
                        Text {
                            text: "独显直连";
                            font-size: 16px;
                        }

                        Switch {
                            checked <=> nvidiaStatusAfterReboot;
                            toggled => { gpuToggled(nvidiaStatusAfterReboot) }
                        }
                    }
                }

                RadioGroup {
                    orientation: horizontal;
                    enabled <=> modeRadioGroupEnabled;
                    RadioButton {
                        text: "办公";
                        checked: perfMode == 0;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 0;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "均衡";
                        checked: perfMode == 1;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 1;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "狂暴";
                        checked: perfMode >= 2 && perfMode < 5;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 2;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "自定义";
                        enabled: onlineStatus;
                        checked: perfMode == 5;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 5;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }
                }

                RadioGroup {
                    orientation: horizontal;
                    enabled: perfMode >= 2 && perfMode < 5 && onlineStatus;
                    RadioButton {
                        text: "静音";
                        checked: perfMode == 3;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 3;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "高能";
                        checked: perfMode == 4;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 4;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }
                }
            }

            // 右栏
            VerticalBox {
                alignment: start;

                InfoCard {
                    title: "控制台在线状态";
                    text: onlineStatus ? "在线" : "离线";
                }

                InfoCard {
                    title: "显卡状态";
                    text: nvidiaStatus ? "独显直连" : "混合输出";
                }

                InfoCard {
                    title: "重启后的显卡状态";
                    text: nvidiaStatusAfterReboot ? "独显直连" : "混合输出";
                }

                InfoCard {
                    title: "GPU 风扇转速百分比";
                    width: self.preferred-width;
                    text: gpuFanRatio + "%";
                }

                InfoCard {
                    title: "CPU 风扇转速百分比";
                    text: cpuFanRatio + "%";
                }

                InfoCard {
                    title: "GPU 风扇转速";
                    text: gpuFan;
                }

                InfoCard {
                    title: "CPU 风扇转速";
                    text: cpuFan;
                }
            }
        }
    }

    in-out property <bool> show_acpi_call_alert: false;
    AlertDialog {
        is_open: show_acpi_call_alert;
        title: "需要安装 ACPI Call";
        text: "未在你的设备中找到 /proc/acpi/call 或安装后未重启, 请安装并重启电脑\n安装方法取决于你使用的 Linux 发行版\n如:\nsudo apt install acpi-call-dkms\nsudo pacman -S acpi_call-dkms";
        confirm_text: "确定";
        confirmed => { show_acpi_call_alert = false; }
    }

    AlertDialog {
        is_open: show_reboot_alert;
        title: "需要重启";
        text: "需要重启以应用显卡设置, 是否立即重启?";
        confirm_text: "确定";
        cancel_text: "稍后";
        confirmed => {
            show_reboot_alert = false;
            reboot();
        }
        canceled => { show_reboot_alert = false; }
    }
}
