import {
    AboutSlint,
    VerticalBox,
    Button,
    HorizontalBox,
    StandardButton,
    Button,
    Palette,
    ScrollView,
    Switch,
    RadioGroup,
} from "std-widgets.slint";



export component MainWindow inherits Window {
    callback button_clicked();
    preferred-height: 768px;
    preferred-width: 1024px;
    max-width: 100000px;
    max-height: 100000px;
    background: #E2E2E9;

    in-out property <bool> onlineStatus;
    in-out property <bool> nvidiaStatus;
    in-out property <bool> nvidiaStatusAfterReboot;
    in-out property <int> perfMode:-1;
    in-out property <bool> modeRadioGroupEnabled:false;
    in-out property <float> cpuFanRatio:-1;
    in-out property <float> gpuFanRatio:-1;
    in-out property <int> cpuFan:-1;
    in-out property <int> gpuFan:-1;
    // 应用完成初始化
    in-out property <bool> initialized: false;

    callback onlineStatusToggled(bool);
    callback gpuToggled(bool);
    callback perfModeChange(int);

    ScrollView {
        HorizontalLayout {
            // 左栏
            VerticalBox {
                alignment: start;
                Text {
                    text: "Control Panel";
                    font-size: 36px;
                }

                Rectangle {
                    height: self.preferred-height;
                    background: #FFFFFF;
                    border-radius: 8px;
                    HorizontalBox {
                        Text {
                            text: "控制台在线状态";
                            font-size: 16px;
                        }

                        Switch {
                            checked <=> onlineStatus;
                            toggled => { onlineStatusToggled(onlineStatus) }
                        }
                    }
                }

                Rectangle {
                    height: self.preferred-height;
                    background: #FFFFFF;
                    border-radius: 8px;
                    HorizontalBox {
                        Text {
                            text: "独显直连";
                            font-size: 16px;
                        }

                        Switch {
                            checked <=> nvidiaStatusAfterReboot;
                            toggled => { gpuToggled(nvidiaStatusAfterReboot) }
                        }
                    }
                }

                RadioGroup {
                    orientation: horizontal;
                    enabled <=> modeRadioGroupEnabled;
                    RadioButton {
                        text: "办公";
                        checked: perfMode == 0;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 0;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "均衡";
                        checked: perfMode == 1;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 1;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "狂暴";
                        checked: perfMode >= 2 && perfMode < 5;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 2;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "自定义";
                        enabled: onlineStatus;
                        checked: perfMode == 5;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 5;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }
                }

                RadioGroup {
                    orientation: horizontal;
                    enabled: perfMode >= 2 && perfMode < 5 && onlineStatus;
                    RadioButton {
                        text: "静音";
                        checked: perfMode == 3;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 3;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }

                    RadioButton {
                        text: "高能";
                        checked: perfMode == 4;
                        toggled => {
                            if (initialized && self.checked) {
                                perfMode = 4;
                                modeRadioGroupEnabled = false;
                                perfModeChange(perfMode);
                            }
                        }
                    }
                }
            }

            // 右栏
            VerticalBox {
                alignment: start;

                Rectangle {
                    background: #FFFFFF;
                    border-radius: 8px;
                    VerticalBox {
                        Text {
                            text: "控制台在线状态";
                            font-size: 16px;
                            color: #405F90;
                        }

                        Text {
                            text: onlineStatus ? "在线" : "离线";
                            font-size: 24px;
                            font-weight: 0;
                        }
                    }
                }

                Rectangle {
                    background: #FFFFFF;
                    border-radius: 8px;
                    VerticalBox {
                        Text {
                            text: "显卡状态";
                            font-size: 16px;
                            color: #405F90;
                        }

                        Text {
                            text: nvidiaStatus ? "独显直连" : "混合输出";
                            font-size: 24px;
                            font-weight: 0;
                        }
                    }
                }

                Rectangle {
                    background: #FFFFFF;
                    border-radius: 8px;
                    VerticalBox {
                        Text {
                            text: "重启后的显卡状态";
                            font-size: 16px;
                            color: #405F90;
                        }

                        Text {
                            text: nvidiaStatusAfterReboot ? "独显直连" : "混合输出";
                            font-size: 24px;
                            font-weight: 0;
                        }
                    }
                }

                Rectangle {
                    width: self.preferred-width;
                    background: #FFFFFF;
                    border-radius: 8px;
                    VerticalBox {
                        Text {
                            text: "GPU 风扇转速百分比";
                            font-size: 16px;
                            color: #405F90;
                        }

                        Text {
                            text: gpuFanRatio + "%";
                            font-size: 24px;
                            font-weight: 0;
                        }
                    }
                }

                Rectangle {
                    background: #FFFFFF;
                    border-radius: 8px;
                    VerticalBox {
                        Text {
                            text: "CPU 风扇转速百分比";
                            font-size: 16px;
                            color: #405F90;
                        }

                        Text {
                            text: cpuFanRatio + "%";
                            font-size: 24px;
                            font-weight: 0;
                        }
                    }
                }

                Rectangle {
                    background: #FFFFFF;
                    border-radius: 8px;
                    VerticalBox {
                        Text {
                            text: "GPU 风扇转速";
                            font-size: 16px;
                            color: #405F90;
                        }

                        Text {
                            text: gpuFan;
                            font-size: 24px;
                            font-weight: 0;
                        }
                    }
                }

                Rectangle {
                    background: #FFFFFF;
                    border-radius: 8px;
                    VerticalBox {
                        Text {
                            text: "CPU 风扇转速";
                            font-size: 16px;
                            color: #405F90;
                        }

                        Text {
                            text: cpuFan;
                            font-size: 24px;
                            font-weight: 0;
                        }
                    }
                }
            }
        }
    }

    in-out property <bool> show_alert: false;
    if show_alert: Rectangle {
        background: #00000066;

        Rectangle {
            width: 320px;
            height: 220px;
            background: #ffffff;
            border-radius: 12px;

            VerticalBox {
                padding: 20px;
                alignment: space-between;

                Text {
                    text: "需要安装 ACPI Call";
                    font-size: 18px;
                    font-weight: 700;
                }

                Text {
                    text: "未在你的设备中找到 /proc/acpi/call 或安装后未重启, 请安装并重启电脑\n安装方法取决于你的 Linux 发行版\n如:\nsudo pacman -S acpi_call-dkms";
                    color: #333333;
                    wrap: word-wrap;
                }

                Button {
                    text: "确定";
                    primary: true;
                    clicked => {
                        show_alert = false;
                    }
                }
            }
        }
    }
}
